ce204_hw4_library.PayPayPal Class Reference
Public Member Functions
boolean PaymentDetails ()
Retrieves the payment details. This method retrieves the payment details for the PayPal payment strategy.
void PaySystem (int price)
Performs the PayPal payment. This method performs the PayPal payment for the car rental.
void CollectPaymentSystemDetails ()
Collects the payment system details. This method collects the necessary details for the PayPal payment system.
int getMoney ()
Retrieves the total amount of money available in the PayPal account. This method retrieves the total amount of money available in the PayPal account.
void setMoney (int i)
Sets the total amount of money available in the PayPal account. This method sets the total amount of money available in the PayPal account.
PayPalSystem getPayPalCard ()
Retrieves the PayPal system. This method retrieves the PayPal system.
Detailed Description
Definition at line 11 of file PayPayPal.java.
Member Function Documentation
CollectPaymentSystemDetails()
void ce204_hw4_library.PayPayPal.CollectPaymentSystemDetails ()
Collects the payment system details. This method collects the necessary details for the PayPal payment system.
Implements ce204_hw4_library.CarPaymentStrategyPattern.
Definition at line 58 of file PayPayPal.java.
                                            {
    payPal = new PayPalSystem("abc@gmail.com", "password123");
  }
getMoney()
int ce204_hw4_library.PayPayPal.getMoney ()
Retrieves the total amount of money available in the PayPal account. This method retrieves the total amount of money available in the PayPal account.
Returns
The total amount of money available in the PayPal account.
Definition at line 69 of file PayPayPal.java.
                        {
    return totalMoney;
  }
Referenced by ce204_hw4_library.PayPayPal.PaySystem().
getPayPalCard()
PayPalSystem ce204_hw4_library.PayPayPal.getPayPalCard ()
Retrieves the PayPal system. This method retrieves the PayPal system.
Returns
The PayPal system.
Definition at line 89 of file PayPayPal.java.
                                      {
    return payPal;
  }
PaymentDetails()
boolean ce204_hw4_library.PayPayPal.PaymentDetails ()
Retrieves the payment details. This method retrieves the payment details for the PayPal payment strategy.
Returns
true, indicating that payment details are available.
Implements ce204_hw4_library.CarPaymentStrategyPattern.
Definition at line 34 of file PayPayPal.java.
                                  {
    return true;
  }
PaySystem()
void ce204_hw4_library.PayPayPal.PaySystem (int price)
Performs the PayPal payment. This method performs the PayPal payment for the car rental.
Parameters
price The amount of money used for the payment.
Implements ce204_hw4_library.CarPaymentStrategyPattern.
Definition at line 45 of file PayPayPal.java.
                                   {
    System.out.println("Paying " + price + " using Credit Card.");
    setMoney(getMoney() - price);
    System.out.println(getMoney() + " remanined in the card.");
    System.out.println("You rented the car");
  }
References ce204_hw4_library.PayPayPal.getMoney(), and ce204_hw4_library.PayPayPal.setMoney().
setMoney()
void ce204_hw4_library.PayPayPal.setMoney (int i)
Sets the total amount of money available in the PayPal account. This method sets the total amount of money available in the PayPal account.
Parameters
i The total amount of money to be set in the PayPal account.
Definition at line 79 of file PayPayPal.java.
                              {
    // TODO Auto-generated method stub
    totalMoney = i;
  }
Referenced by ce204_hw4_library.PayPayPal.PaySystem().
The documentation for this class was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_library/PayPayPal.java