ce204_hw4_library.MenuServices Class Reference
Public Member Functions
void designSelectCarType ()
Designs the car type selection menu.
void designAdminMenu ()
Designs the admin menu.
void designMainMenu ()
Designs the main menu.
void designCustomerMenu ()
Designs the customer menu.
Detailed Description
Definition at line 3 of file MenuServices.java.
Member Function Documentation
designAdminMenu()
void ce204_hw4_library.MenuServices.designAdminMenu ()
Designs the admin menu.
Implements ce204_hw4_library.MenuServicesInterface.
Definition at line 16 of file MenuServices.java.
                                { // Admin's Main Menu
    System.out.print("+---------------------------------------------+\n"
                     + "| Car Rental Service |\n"
                     + "+---------------------------------------------+\n" + "\n"
                     + " ADMIN MENU \n" + "1. List Cars\n" + "2. Add Car\n"
                     + "3. Delete Car\n" + "4. Log-out\n" + "5. Exit\n");
  }
Referenced by ce204_hw4_app.Main.AdminMenu().
designCustomerMenu()
void ce204_hw4_library.MenuServices.designCustomerMenu ()
Designs the customer menu.
Implements ce204_hw4_library.MenuServicesInterface.
Definition at line 33 of file MenuServices.java.
                                   { // A customer Menu
    System.out.print("+---------------------------------------------+\n"
                     + "| Car Rental Service |\n"
                     + "+---------------------------------------------+\n" + "\n"
                     + " CUSTOMER MENU \n" + "1. Rent a Car\n" + "2. Logout\n"
                     + "3. Exit\n\n");
  }
Referenced by ce204_hw4_app.Main.CustomerMenu().
designMainMenu()
void ce204_hw4_library.MenuServices.designMainMenu ()
Designs the main menu.
Implements ce204_hw4_library.MenuServicesInterface.
Definition at line 25 of file MenuServices.java.
                               { // Main menu
    System.out.print("+---------------------------------------------+\n"
                     + "| Car Rental Service |\n"
                     + "+---------------------------------------------+\n" + "\n"
                     + " MAIN MENU \n" + "1. Register\n" + "2. Login\n" + "3. Exit\n");
  }
Referenced by ce204_hw4_app.Main.MainMenu().
designSelectCarType()
void ce204_hw4_library.MenuServices.designSelectCarType ()
Designs the car type selection menu.
Implements ce204_hw4_library.MenuServicesInterface.
Definition at line 6 of file MenuServices.java.
                                    { // Car Adding Menu
    System.out.print("+---------------------------------------------+\n"
                     + "| Car Rental Service |\n"
                     + "+---------------------------------------------+\n" + "\n"
                     + " Add Car \n" + "1. Add Sedan\n" + "2. Add SUV\n"
                     + "3. Add Station Wagon\n" + "4. Add PickUp\n" + "5. Add Hatchback\n" + "6. Add Cabrio\n"
                     + "\nEnter your choice: ");
  }
Referenced by ce204_hw4_app.Main.AdminMenu().
The documentation for this class was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_library/MenuServices.java