ce204_hw4_app.Main Class Reference
Represents the main application class.
Public Member Functions
Main (List< User > userList, MenuServices MENU_DISPLAY_SERVICES, LoginServices loginServices, RegistrationServices registrationServices)
Constructs a new Main object.
void AdminMenu ()
Displays the admin menu and handles admin options.
void MainMenu ()
Displays the main menu and handles user options.
void CustomerMenu ()
Displays the customer menu and handles customer options.
void DefaulMainCars ()
Initializes the main car list with default cars.
void displayCar (RentCarInterface car)
Displays the details of a car.
void LogOut ()
Logs out the user and returns to the main menu.
Public Attributes
List< RentCarInterface > rentalCars = new ArrayList<>()
Scanner INPUT = new Scanner(System.in)
Detailed Description
Represents the main application class.
This class contains the main logic of the application and handles the different menus and user interactions.
Definition at line 18 of file Main.java.
Constructor & Destructor Documentation
Main()
ce204_hw4_app.Main.Main (List< User > userList, MenuServices MENU_DISPLAY_SERVICES, LoginServices loginServices, RegistrationServices registrationServices)
Constructs a new Main object.
Parameters
userList The list of users in the application.
MENU_DISPLAY_SERVICES The menu display services.
loginServices The login services.
registrationServices The registration services.
Definition at line 39 of file Main.java.
                                                         {
    this.MENU_DISPLAY_SERVICES = MENU_DISPLAY_SERVICES;
    this.loginServices = loginServices;
    this.registrationServices = registrationServices;
  }
Member Function Documentation
AdminMenu()
void ce204_hw4_app.Main.AdminMenu ()
Displays the admin menu and handles admin options.
Definition at line 48 of file Main.java.
                          {
    Scanner scanner = new Scanner(System.in);
    do {
      System.out.println();
      MENU_DISPLAY_SERVICES.designAdminMenu();
      System.out.println("Please, choose your option from down below: ");
      int option = INPUT.nextInt();
      switch (option) {
        case 1: // List Car
          System.out.println("\nRental Cars:\n");
          int i = 0;
          if (rentalCars.isEmpty()) {
            System.out.println("No cars available.");
          } else {
            System.out.println(
              "+------Brand---------Model-------Car Year-----Fuel Type----Color----Price---Number of Seats-------+\n");
            for (RentCarInterface rentalCar : rentalCars) {
              i++;
              System.out.print(i + ". => ");
              displayCar(rentalCar);
            }
          }
          break;
        case 2: // Add Car
          MENU_DISPLAY_SERVICES.designSelectCarType();
          String carType = "";
          int selectCarType = Integer.parseInt(scanner.nextLine());
          switch (selectCarType) {
            case 1: {
              carType = "modelsedan";
              break;
            }
            case 2: {
              carType = "modelsuv";
              break;
            }
            case 3: {
              carType = "modelstationwagon";
              break;
            }
            case 4: {
              carType = "modelpickup";
              break;
            }
            case 5: {
              carType = "modelhatchback";
              break;
            }
            case 6: {
              carType = "modelcabrio";
              break;
            }
            default:
              System.out.println("Invalid choose only betwen displayed options!");
              return;
          }
          System.out.print("Enter Brand: ");
          String getBrand = scanner.nextLine();
          System.out.print("Enter Model: ");
          String getModel = scanner.nextLine();
          System.out.print("Enter Car Year: ");
          int getCarYear = Integer.parseInt(scanner.nextLine());
          System.out.print("Enter Fuel Type: ");
          String getFuelType = scanner.nextLine();
          System.out.print("Enter Color: ");
          String getColor = scanner.nextLine();
          System.out.print("Enter Price: ");
          int getPrice = Integer.parseInt(scanner.nextLine());
          System.out.print("Enter Number of Seats: ");
          int getSeatsNumber = Integer.parseInt(scanner.nextLine());
          RentCarInterface car = FactoryMethodPatternCar.createCar(carType, getSeatsNumber, getPrice, getColor,
                                 getModel, getBrand, getFuelType, getCarYear);
          paymentSystemService.setMoney(getPrice);
          rentalCars.add(car);
          System.out.println("\nCar added successfully!");
          break;
        case 3: // Delete Car
          System.out.print("\nEnter the index of the car to delete: ");
          int index = Integer.parseInt(scanner.nextLine());
          if (index >= 0 && index < rentalCars.size() + 1) {
            rentalCars.remove(index - 1);
            System.out.println("Car deleted successfully!");
          } else {
            System.out.println("Invalid index!");
          }
          break;
        case 4: // Logout
          LogOut();
          break;
        case 5: // Exit app
          loginServices.exitApp();
          return;
        default: // In case of picking a wrong option
          System.out.println("Invalid choice. Please, choose only between displayed options!");
          break;
      }
    } while (loginServices.isLoggedInAsAdmin(loginServices.getLoggedInUser()));
  }
References ce204_hw4_library.FactoryMethodPatternCar.createCar(), ce204_hw4_library.MenuServices.designAdminMenu(), ce204_hw4_library.MenuServices.designSelectCarType(), ce204_hw4_app.Main.displayCar(), ce204_hw4_library.LoginServices.exitApp(), ce204_hw4_library.LoginServices.getLoggedInUser(), ce204_hw4_app.Main.INPUT, ce204_hw4_library.LoginServices.isLoggedInAsAdmin(), ce204_hw4_app.Main.LogOut(), ce204_hw4_app.Main.rentalCars, and ce204_hw4_library.PaymentSystemService.setMoney().
Referenced by ce204_hw4_app.Main.MainMenu().
CustomerMenu()
void ce204_hw4_app.Main.CustomerMenu ()
Displays the customer menu and handles customer options.
Definition at line 207 of file Main.java.
                             {
    do {
      System.out.println();
      MENU_DISPLAY_SERVICES.designCustomerMenu();
      System.out.println("Please, choose your option from down below: ");
      int option = INPUT.nextInt();
      switch (option) {
        case 1: // Rent a Car
          System.out.println("\nRental Cars:\n");
          int i = 0;
          if (rentalCars.isEmpty()) {
            System.out.println("No cars available.");
          } else {
            for (RentCarInterface rentalACar : rentalCars) {
              i++;
              System.out.println(
                "+------Brand---------Model-------Car Year-----Fuel Type----Color----Price---Number of Seats-------+\n");
              System.out.print(i + ". => ");
              displayCar(rentalACar);
            }
            Scanner scanner = new Scanner(System.in);
            int index;
            while (true) {
              System.out.println("\nEnter the index of the car: ");
              index = Integer.parseInt(scanner.nextLine());
              if (index >= 0 && index < rentalCars.size() + 1) {
                paymentSystemService.setSelectedCarIndex(index - 1);
                break;
              } else {
                System.out.println("Invalid index!");
              }
            }
            int paymentType;
            while (true) {
              System.out.println("1 - Credit Card");
              System.out.println("2 - PayPal");
              System.out.println("3 - Cash");
              System.out.println("Choose the payment type:");
              paymentType = Integer.parseInt(scanner.next());
              if (paymentType == 1) {
                paymentSystemService.setStrategyPattern(payCreditCard);
                Bill.displayBill(rentalCars.get(index - 1), "Credit Cart");
                break;
              } else if (paymentType == 2) {
                paymentSystemService.setStrategyPattern(payPayPal);
                Bill.displayBill(rentalCars.get(index - 1), "PayPal");
                break;
              } else if (paymentType == 3) {
                paymentSystemService.setStrategyPattern(payCash);
                Bill.displayBill(rentalCars.get(index - 1), "Cash");
                break;
              } else {
                return;
              }
            }
            paymentSystemService.proccessOrder();
            paymentSystemService.removeMoney(index - 1);
            rentalCars.remove(index - 1);
            System.out.println("Kaç gün sonra kiralaycaksınız:");
            int Rentindex = Integer.parseInt(scanner.next());
            System.out.print("Bildirim Almak ve Abone Olmak istiyorsanız 1'i tuşlayın");
            int selecetSubs = Integer.parseInt(scanner.next());
            if (selecetSubs == 1) {
              NotificationTime timer = new NotificationTime(Rentindex, 2);
              CarCustomer customer = new CarCustomer("Customer");
              timer.addObserver(customer);
              for (int a = timer.getRemainingNoti(); a >= 0; a--) {
                timer.setRemainingNoti(a);
              }
            }
          }
          break;
        case 2: // Logout
          LogOut();
          break;
        case 3: // Exit app
          loginServices.exitApp();
          return;
        default: // In case of picking a wrong option
          System.out.println("Invalid choice. Please, choose only between displayed options!");
          break;
      }
    } while (loginServices.isLoggedInAsCustomer(loginServices.getLoggedInUser()));
  }
References ce204_hw4_library.CustomerObserverable.addObserver(), ce204_hw4_library.MenuServices.designCustomerMenu(), ce204_hw4_app.Bill.displayBill(), ce204_hw4_app.Main.displayCar(), ce204_hw4_library.LoginServices.exitApp(), ce204_hw4_library.LoginServices.getLoggedInUser(), ce204_hw4_library.NotificationTime.getRemainingNoti(), ce204_hw4_app.Main.INPUT, ce204_hw4_library.LoginServices.isLoggedInAsCustomer(), ce204_hw4_app.Main.LogOut(), ce204_hw4_library.PaymentSystemService.proccessOrder(), ce204_hw4_library.PaymentSystemService.removeMoney(), ce204_hw4_app.Main.rentalCars, ce204_hw4_library.NotificationTime.setRemainingNoti(), ce204_hw4_library.PaymentSystemService.setSelectedCarIndex(), and ce204_hw4_library.PaymentSystemService.setStrategyPattern().
Referenced by ce204_hw4_app.Main.MainMenu().
DefaulMainCars()
void ce204_hw4_app.Main.DefaulMainCars ()
Initializes the main car list with default cars.
Definition at line 309 of file Main.java.
                               {
    RentCarInterface carOne = FactoryMethodPatternCar.createCar("modelsedan", 1, 1, "sedan", "sedan", "sedan",
                              "sedan", 1);
    rentalCars.add(carOne);
    paymentSystemService.setMoney(1);
  }
References ce204_hw4_library.FactoryMethodPatternCar.createCar(), ce204_hw4_app.Main.rentalCars, and ce204_hw4_library.PaymentSystemService.setMoney().
displayCar()
void ce204_hw4_app.Main.displayCar (RentCarInterface car)
Displays the details of a car.
Parameters
car The car to display.
Definition at line 321 of file Main.java.
                                               {
    System.out.println(car.getCarBrand().toUpperCase() + " => " + car.getCarModel().toUpperCase() + " => "
                       + car.getCarColor() + " => " + car.getCarFuelType().toUpperCase() + " => "
                       + car.getCarColor().toUpperCase() + " => " + car.getCarPrice() + " => "
                       + car.getCarSeatsNumber() + "\n");
  }
References ce204_hw4_library.RentCarInterface.getCarBrand(), ce204_hw4_library.RentCarInterface.getCarColor(), ce204_hw4_library.RentCarInterface.getCarFuelType(), ce204_hw4_library.RentCarInterface.getCarModel(), ce204_hw4_library.RentCarInterface.getCarPrice(), and ce204_hw4_library.RentCarInterface.getCarSeatsNumber().
Referenced by ce204_hw4_app.Main.AdminMenu(), and ce204_hw4_app.Main.CustomerMenu().
LogOut()
void ce204_hw4_app.Main.LogOut ()
Logs out the user and returns to the main menu.
Definition at line 330 of file Main.java.
                       {
    System.out.println("Log-out successfully!");
    MainMenu();
  }
References ce204_hw4_app.Main.MainMenu().
Referenced by ce204_hw4_app.Main.AdminMenu(), and ce204_hw4_app.Main.CustomerMenu().
MainMenu()
void ce204_hw4_app.Main.MainMenu ()
Displays the main menu and handles user options.
Definition at line 169 of file Main.java.
                         {
    do {
      System.out.println();
      MENU_DISPLAY_SERVICES.designMainMenu();
      System.out.println("Username for Admin: admin, password:0000 /// Username for Customer: ugur, password:1234");
      System.out.println("If you don't have an account yet, register now for free!");
      System.out.println("Please, choose your option from down below: ");
      int option = INPUT.nextInt();
      switch (option) {
        case 1: // Registration
          registrationServices.initiateRegistration(loginServices);
          break;
        case 2: // Login
          loginServices.initiateLogIn();
          if (loginServices.isLoggedInAsAdmin(loginServices.getLoggedInUser())) {
            AdminMenu();
          } else {
            CustomerMenu();
          }
          break;
        case 3: // Exit app
          loginServices.exitApp();
          return;
        default: // In case of picking a wrong option
          System.out.println("Wrong option. Please, try again!");
          break;
      }
    } while (!loginServices.isLoggedIn(loginServices.getLoggedInUser()));
  }
References ce204_hw4_app.Main.AdminMenu(), ce204_hw4_app.Main.CustomerMenu(), ce204_hw4_library.MenuServices.designMainMenu(), ce204_hw4_library.LoginServices.exitApp(), ce204_hw4_library.LoginServices.getLoggedInUser(), ce204_hw4_library.LoginServices.initiateLogIn(), ce204_hw4_library.RegistrationServices.initiateRegistration(), ce204_hw4_app.Main.INPUT, ce204_hw4_library.LoginServices.isLoggedIn(), and ce204_hw4_library.LoginServices.isLoggedInAsAdmin().
Referenced by ce204_hw4_app.Main.LogOut().
Member Data Documentation
INPUT
Scanner ce204_hw4_app.Main.INPUT = new Scanner(System.in)
Definition at line 21 of file Main.java.
Referenced by ce204_hw4_app.Main.AdminMenu(), ce204_hw4_app.Main.CustomerMenu(), and ce204_hw4_app.Main.MainMenu().
rentalCars
List<RentCarInterface> ce204_hw4_app.Main.rentalCars = new ArrayList<>()
Definition at line 20 of file Main.java.
Referenced by ce204_hw4_app.Main.AdminMenu(), ce204_hw4_app.Main.CustomerMenu(), and ce204_hw4_app.Main.DefaulMainCars().
The documentation for this class was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_app/Main.java