ce204_hw4_library.LoginServices Class Reference
Represents the login services for the application.
Public Member Functions
LoginServices (List< User > userList)
Constructs a new LoginServices object with the specified user list.
User getLoggedInUser ()
Gets the currently logged in user.
User validateLogIn (String userName, String password)
Validates the login credentials.
User doLogIn (String userName, String password)
Performs the login process.
void exitApp ()
Exits the application.
boolean isLoggedIn (User loggedInUser)
Checks if a user is logged in.
boolean isLoggedInAsCustomer (User loggedInUser)
Checks if a user is logged in as a customer.
boolean isLoggedInAsAdmin (User loggedInUser)
Checks if a user is logged in as an admin.
void setLoggedInUser (User loggedInUser)
Sets the logged in user.
User initiateLogIn ()
Initiates the login process.
void displayLogInMenu ()
Displays the login menu.
Public Attributes
Scanner input = new Scanner(System.in)
Detailed Description
Represents the login services for the application.
Definition at line 19 of file LoginServices.java.
Constructor & Destructor Documentation
LoginServices()
ce204_hw4_library.LoginServices.LoginServices (List< User > userList)
Constructs a new LoginServices object with the specified user list.
Parameters
userList The list of users in the system.
Definition at line 30 of file LoginServices.java.
                                            {
    this.userList = userList;
  }
Member Function Documentation
displayLogInMenu()
void ce204_hw4_library.LoginServices.displayLogInMenu ()
Displays the login menu.
Definition at line 158 of file LoginServices.java.
                                 {
    System.out.println("+----------------------------------------------+");
    System.out.println("| LOGIN: |");
    System.out.println("+----------------------------------------------+");
  }
Referenced by ce204_hw4_library.LoginServices.initiateLogIn().
doLogIn()
User ce204_hw4_library.LoginServices.doLogIn (String userName, String password)
Performs the login process.
Parameters
userName The username provided by the user.
password The password provided by the user.
Returns
The logged in User object.
Definition at line 68 of file LoginServices.java.
                                                        {
    if (validateLogIn(userName, password) instanceof Customer) {
      loggedInUser = validateLogIn(userName, password);
      System.out.println("Welcome " + loggedInUser.getFirstName() + " " + loggedInUser.getLastName() + "!");
    } else if (validateLogIn(userName, password) instanceof Admin) {
      loggedInUser = validateLogIn(userName, password);
      System.out.println("Welcome " + loggedInUser.getFirstName() + " " + loggedInUser.getLastName() + "!");
    }
    return loggedInUser;
  }
References ce204_hw4_app.User.getFirstName(), ce204_hw4_app.User.getLastName(), and ce204_hw4_library.LoginServices.validateLogIn().
Referenced by ce204_hw4_library.LoginServices.initiateLogIn().
exitApp()
void ce204_hw4_library.LoginServices.exitApp ()
Exits the application.
Definition at line 84 of file LoginServices.java.
                        {
    System.out.println("Hope you'll be back soon!");
  }
Referenced by ce204_hw4_app.Main.AdminMenu(), ce204_hw4_app.Main.CustomerMenu(), and ce204_hw4_app.Main.MainMenu().
getLoggedInUser()
User ce204_hw4_library.LoginServices.getLoggedInUser ()
Gets the currently logged in user.
Returns
The currently logged in user.
Definition at line 39 of file LoginServices.java.
                                {
    return loggedInUser;
  }
Referenced by ce204_hw4_app.Main.AdminMenu(), ce204_hw4_app.Main.CustomerMenu(), and ce204_hw4_app.Main.MainMenu().
initiateLogIn()
User ce204_hw4_library.LoginServices.initiateLogIn ()
Initiates the login process.
Returns
The logged in User object.
Definition at line 133 of file LoginServices.java.
                              {
    User loggedIn;
    do {
      System.out.println();
      displayLogInMenu();
      System.out.println("Username:");
      String userName = input.nextLine();
      System.out.println("Password:");
      String password = input.nextLine();
      loggedIn = doLogIn(userName, password);
      if (isLoggedInAsCustomer(loggedIn) || isLoggedInAsAdmin(loggedIn)) {
        System.out.println("Login successfully!!!");
      } else {
        System.out.println("Wrong credentials! Please, try again!");
      }
    } while (!isLoggedIn(loggedIn));
    return loggedIn;
  }
References ce204_hw4_library.LoginServices.displayLogInMenu(), ce204_hw4_library.LoginServices.doLogIn(), ce204_hw4_library.LoginServices.input, ce204_hw4_library.LoginServices.isLoggedIn(), ce204_hw4_library.LoginServices.isLoggedInAsAdmin(), and ce204_hw4_library.LoginServices.isLoggedInAsCustomer().
Referenced by ce204_hw4_app.Main.MainMenu().
isLoggedIn()
boolean ce204_hw4_library.LoginServices.isLoggedIn (User loggedInUser)
Checks if a user is logged in.
Parameters
loggedInUser The user to check.
Returns
true if the user is logged in, false otherwise.
Definition at line 94 of file LoginServices.java.
                                               {
    return loggedInUser != null;
  }
Referenced by ce204_hw4_library.LoginServices.initiateLogIn(), ce204_hw4_library.LoginServices.isLoggedInAsAdmin(), ce204_hw4_library.LoginServices.isLoggedInAsCustomer(), and ce204_hw4_app.Main.MainMenu().
isLoggedInAsAdmin()
boolean ce204_hw4_library.LoginServices.isLoggedInAsAdmin (User loggedInUser)
Checks if a user is logged in as an admin.
Parameters
loggedInUser The user to check.
Returns
true if the user is logged in as an admin, false otherwise.
Definition at line 115 of file LoginServices.java.
                                                      {
    return isLoggedIn(loggedInUser) && loggedInUser.getUserName().equals("admin");
  }
References ce204_hw4_app.User.getUserName(), and ce204_hw4_library.LoginServices.isLoggedIn().
Referenced by ce204_hw4_app.Main.AdminMenu(), ce204_hw4_library.LoginServices.initiateLogIn(), and ce204_hw4_app.Main.MainMenu().
isLoggedInAsCustomer()
boolean ce204_hw4_library.LoginServices.isLoggedInAsCustomer (User loggedInUser)
Checks if a user is logged in as a customer.
Parameters
loggedInUser The user to check.
Returns
true if the user is logged in as a customer, false otherwise.
Definition at line 105 of file LoginServices.java.
                                                         {
    return isLoggedIn(loggedInUser) && !loggedInUser.getUserName().equals("customer");
  }
References ce204_hw4_app.User.getUserName(), and ce204_hw4_library.LoginServices.isLoggedIn().
Referenced by ce204_hw4_app.Main.CustomerMenu(), and ce204_hw4_library.LoginServices.initiateLogIn().
setLoggedInUser()
void ce204_hw4_library.LoginServices.setLoggedInUser (User loggedInUser)
Sets the logged in user.
Parameters
loggedInUser The user to set as loggedinUser.
Definition at line 124 of file LoginServices.java.
                                                 {
    this.loggedInUser = loggedInUser;
  }
validateLogIn()
User ce204_hw4_library.LoginServices.validateLogIn (String userName, String password)
Validates the login credentials.
Parameters
userName The username provided by the user.
password The password provided by the user.
Returns
The User object if the credentials are valid, null otherwise.
Definition at line 50 of file LoginServices.java.
                                                              {
    for (User currentUser : userList) {
      if (userName.equals(currentUser.getUserName()) && password.equals(currentUser.getPassword())) {
        return currentUser;
      }
    }
    return null;
  }
Referenced by ce204_hw4_library.LoginServices.doLogIn().
Member Data Documentation
input
Scanner ce204_hw4_library.LoginServices.input = new Scanner(System.in)
Definition at line 21 of file LoginServices.java.
Referenced by ce204_hw4_library.LoginServices.initiateLogIn().
The documentation for this class was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_library/LoginServices.java