ce204_hw4_app.Bill Class Reference
Represents a bill for a rented car.
Static Public Member Functions
static void displayBill (RentCarInterface car, String paymentsystemType)
Detailed Description
Represents a bill for a rented car.
This class is responsible for displaying the bill details for a rented car, including its features and payment information.
Definition at line 14 of file Bill.java.
Member Function Documentation
displayBill()
static void ce204_hw4_app.Bill.displayBill (RentCarInterface car, String paymentsystemType) [static]
Definition at line 30 of file Bill.java.
                                                                                 {
    System.out.print("+---------------------------------------------+\n" +
                     "| BILL |\n" +
                     "+---------------------------------------------+\n\n" +
                     "Car Brand: " + car.getCarBrand().toUpperCase() + "\n" +
                     "Car Model: " + car.getCarModel().toUpperCase() + "\n" +
                     "Car Year: " + car.getCarModelYear() + "\n" +
                     "Car Fuel: " + car.getCarFuelType().toUpperCase() + "\n" +
                     "Car Color: " + car.getCarColor().toUpperCase() + "\n" +
                     "Car Price: " + car.getCarPrice() + "\n" +
                     "Car Seats Number: " + car.getCarSeatsNumber() + "\n" +
                     "Paymet Type: " + paymentsystemType + "\n\n" +
                     "+---------------------------------------------+\n" +
                     "+---------------------------------------------+\n\n");
  }
References ce204_hw4_library.RentCarInterface.getCarBrand(), ce204_hw4_library.RentCarInterface.getCarColor(), ce204_hw4_library.RentCarInterface.getCarFuelType(), ce204_hw4_library.RentCarInterface.getCarModel(), ce204_hw4_library.RentCarInterface.getCarModelYear(), ce204_hw4_library.RentCarInterface.getCarPrice(), and ce204_hw4_library.RentCarInterface.getCarSeatsNumber().
Referenced by ce204_hw4_app.Main.CustomerMenu().
The documentation for this class was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_app/Bill.java