ce204_hw4_app.UserDatabase Class Reference
Represents a database of users in the application.
Static Public Member Functions
static long getShopBalance ()
Returns the shop balance.
static List< User > getAdminList ()
Returns a list of admin users.
static List< User > getCustomerList ()
Returns a list of customer users.
static List< User > getAllUserList ()
Returns a list of all users.
Detailed Description
Represents a database of users in the application.
Definition at line 17 of file UserDatabase.java.
Member Function Documentation
getAdminList()
static List<User> ce204_hw4_app.UserDatabase.getAdminList () [static]
Returns a list of admin users.
Return values
[List<User>] A list of admin users.
Definition at line 33 of file UserDatabase.java.
                                          {
    List<User> adminList = new ArrayList<>();
    adminList.add(new Admin("Admin", "ADMIN", "admin", "0000"));
    adminList.add(new Admin("Alper", "alper", "alper", "admin"));
    adminList.add(new Admin("Sahin", "Sahin", "alper", "123"));
    adminList.add(new Admin("Can", "Alper", "can", "1234"));
    return adminList;
  }
Referenced by ce204_hw4_app.UserDatabase.getAllUserList(), and ce204_hw4_app.App.main().
getAllUserList()
static List<User> ce204_hw4_app.UserDatabase.getAllUserList () [static]
Returns a list of all users.
Return values
[List<User>] A list of all users.
Definition at line 61 of file UserDatabase.java.
                                            {
    List<User> userList = getCustomerList();
    userList.addAll(getAdminList());
    return userList;
  }
References ce204_hw4_app.UserDatabase.getAdminList(), and ce204_hw4_app.UserDatabase.getCustomerList().
getCustomerList()
static List<User> ce204_hw4_app.UserDatabase.getCustomerList () [static]
Returns a list of customer users.
Return values
[List<User>] A list of customer users.
Definition at line 48 of file UserDatabase.java.
                                             {
    List<User> customerList = new ArrayList<>();
    customerList.add(new Customer("Ugur", "Coruh", "ugur", "1234", "2015-03-26"));
    customerList.add(new Customer("Alper", "Sahin", "alper", "1234", "2017-01-12"));
    return customerList;
  }
Referenced by ce204_hw4_app.UserDatabase.getAllUserList(), and ce204_hw4_app.App.main().
getShopBalance()
static long ce204_hw4_app.UserDatabase.getShopBalance () [static]
Returns the shop balance.
Return values
[long] The shop balance.
Definition at line 23 of file UserDatabase.java.
                                      {
    return 0;
  }
The documentation for this class was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_app/UserDatabase.java