ce204_hw4_library.RegistrationServices Class Reference
Represents a registration service for user registration.
Public Member Functions
RegistrationServices (List< User > userList)
Constructs a RegistrationServices instance with the specified user list. This constructor initializes a RegistrationServices instance with the specified user list.
Customer customerRegistrationForm (String firstName, String lastName, String userName, String password, String licenceObtained)
Creates a new customer registration form. This method creates a new customer registration form with the provided user details.
void customerRegistration (Customer customer)
Performs the customer registration. This method performs the customer registration by adding the customer to the user list.
void displayRegistrationMenu ()
Displays the registration menu. This method displays the registration menu.
void initiateRegistration (LoginServices loginService)
Initiates the registration process. This method initiates the registration process by prompting the user to enter their registration details and performs the necessary validation and registration steps.
Public Attributes
Scanner input = new Scanner(System.in)
double diff
Detailed Description
Represents a registration service for user registration.
   The RegistrationServices class implements the
   RegistrationServicesInterface and provides methods for handling
   customer

   registration and managing the registration process.
Definition at line 31 of file RegistrationServices.java.
Constructor & Destructor Documentation
RegistrationServices()
ce204_hw4_library.RegistrationServices.RegistrationServices (List< User > userList)
Constructs a RegistrationServices instance with the specified user list. This constructor initializes a RegistrationServices instance with the specified user list.
Parameters
userList The list of users to be managed by the registration service.
Definition at line 45 of file RegistrationServices.java.
                                                   {
    this.userList = userList;
  }
Member Function Documentation
customerRegistration()
void ce204_hw4_library.RegistrationServices.customerRegistration (Customer customer)
Performs the customer registration. This method performs the customer registration by adding the customer to the user list.
Parameters
customer The Customer object representing the customer registration form.
Implements ce204_hw4_library.RegistrationServicesInterface.
Definition at line 75 of file RegistrationServices.java.
                                                      {
    System.out.println("Registration complete!");
    userList.add(customer);
  }
Referenced by ce204_hw4_library.RegistrationServices.initiateRegistration().
customerRegistrationForm()
Customer ce204_hw4_library.RegistrationServices.customerRegistrationForm (String firstName, String lastName, String userName, String password, String licenceObtained)
Creates a new customer registration form. This method creates a new customer registration form with the provided user details.
Parameters
firstName The first name of the customer.
lastName The last name of the customer.
userName The username of the customer.
password The password of the customer.
licenceObtained The date the driver's license was obtained by the customer.
Returns
A Customer object representing the customer registration form.
Implements ce204_hw4_library.RegistrationServicesInterface.
Definition at line 62 of file RegistrationServices.java.
                              {
    return new Customer(firstName, lastName, userName, password, licenceObtained);
  }
Referenced by ce204_hw4_library.RegistrationServices.initiateRegistration().
displayRegistrationMenu()
void ce204_hw4_library.RegistrationServices.displayRegistrationMenu ()
Displays the registration menu. This method displays the registration menu.
Implements ce204_hw4_library.RegistrationServicesInterface.
Definition at line 86 of file RegistrationServices.java.
                                        {
    System.out.println("+----------------------------------------------+");
    System.out.println("| REGISTER |");
    System.out.println("+----------------------------------------------+");
  }
Referenced by ce204_hw4_library.RegistrationServices.initiateRegistration().
initiateRegistration()
void ce204_hw4_library.RegistrationServices.initiateRegistration (LoginServices loginService)
Initiates the registration process. This method initiates the registration process by prompting the user to enter their registration details and performs the necessary validation and registration steps.
Parameters
loginService The LoginServices object used for the registration process.
Implements ce204_hw4_library.RegistrationServicesInterface.
Definition at line 101 of file RegistrationServices.java.
                                                               {
    System.out.println();
    displayRegistrationMenu();
    System.out.println("First Name:");
    String firstName = input.next();
    System.out.println("Last Name:");
    String lastName = input.next();
    System.out.println("Username:");
    String userName = input.next();
    System.out.println("Password:");
    String password = input.next();
    System.out.println("Driver's license date:[yyyy-MM-dd]");
    System.out.println("(Must be at least 2 years)");
    String licenceObtained = input.next();
    try {
      Date date = dateFormat.parse(String.valueOf(licenceObtained));
      dateFormat = new SimpleDateFormat("EEE, yyyy MMM d");
      Date currentDate = new Date();
      DecimalFormat df = new DecimalFormat("#.##");
      long diffInMillies = Math.abs(currentDate.getTime() - date.getTime());
      diff = (double) (diffInMillies / (1000 * 60 * 60 * 24 * 365.25));
      System.out.println("Licence usage time: " + df.format(diff) + " year");
    } catch (ParseException e) {
      System.out.println("Parse Exception");
    }
    if (diff < 2) {
      System.out.println("License usage time is not enough");
    } else {
      customerRegistration(customerRegistrationForm(firstName, lastName, userName, password, licenceObtained));
    }
  }
References ce204_hw4_library.RegistrationServices.customerRegistration(), ce204_hw4_library.RegistrationServices.customerRegistrationForm(), ce204_hw4_library.RegistrationServices.diff, ce204_hw4_library.RegistrationServices.displayRegistrationMenu(), and ce204_hw4_library.RegistrationServices.input.
Referenced by ce204_hw4_app.Main.MainMenu().
Member Data Documentation
diff
double ce204_hw4_library.RegistrationServices.diff
Definition at line 36 of file RegistrationServices.java.
Referenced by ce204_hw4_library.RegistrationServices.initiateRegistration().
input
Scanner ce204_hw4_library.RegistrationServices.input = new Scanner(System.in)
Definition at line 33 of file RegistrationServices.java.
Referenced by ce204_hw4_library.RegistrationServices.initiateRegistration().
The documentation for this class was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_library/RegistrationServices.java