ce204_hw4_library.PaymentSystemService Class Reference
Represents a payment system service for car rentals.
Public Member Functions
void proccessOrder ()
Processes the car rental order. This method processes the car rental order by collecting the payment system details and performing the payment using the selected payment strategy. It checks if payment details are available before making the payment.
void setMoney (int costInput)
Sets the amount of money for a car rental. This method sets the amount of money for a car rental by adding it to the list of money amounts.
void removeMoney (int costInput)
Removes the amount of money for a car rental. This method removes the amount of money for a car rental from the list of money amounts.
int getTotalMoney ()
Retrieves the total amount of money for the selected car rental. This method retrieves the total amount of money for the selected car rental based on the car index.
void setSelectedCarIndex (int carIndexInput)
Sets the index of the selected car. This method sets the index of the selected car in the carIndex variable.
void setStrategyPattern (CarPaymentStrategyPattern strategyPatternSelected)
Sets the payment strategy pattern. This method sets the payment strategy pattern to be used for the car rental payment.
List< Integer > getMoney ()
Retrieves the list of money amounts. This method retrieves the list of money amounts.
Detailed Description
Represents a payment system service for car rentals.
   The PaymentSystemService class provides methods for processing car
   rental payments using different payment strategies.

   It manages the payment process and keeps track of the total money
   available for each car rental.
Definition at line 24 of file PaymentSystemService.java.
Member Function Documentation
getMoney()
List<Integer> ce204_hw4_library.PaymentSystemService.getMoney ()
Retrieves the list of money amounts. This method retrieves the list of money amounts.
Returns
The list of money amounts.
Definition at line 101 of file PaymentSystemService.java.
                                  {
    return money;
  }
getTotalMoney()
int ce204_hw4_library.PaymentSystemService.getTotalMoney ()
Retrieves the total amount of money for the selected car rental. This method retrieves the total amount of money for the selected car rental based on the car index.
Returns
The total amount of money for the selected car rental.
Definition at line 71 of file PaymentSystemService.java.
                             {
    return money.get(carIndex);
  }
Referenced by ce204_hw4_library.PaymentSystemService.proccessOrder().
proccessOrder()
void ce204_hw4_library.PaymentSystemService.proccessOrder ()
Processes the car rental order. This method processes the car rental order by collecting the payment system details and performing the payment using the selected payment strategy. It checks if payment details are available before making the payment.
Definition at line 36 of file PaymentSystemService.java.
                              {
    strategyPattern.CollectPaymentSystemDetails();
    if (strategyPattern.PaymentDetails()) {
      strategyPattern.PaySystem(getTotalMoney());
    }
  }
References ce204_hw4_library.CarPaymentStrategyPattern.CollectPaymentSystemDetails(), ce204_hw4_library.PaymentSystemService.getTotalMoney(), ce204_hw4_library.CarPaymentStrategyPattern.PaymentDetails(), and ce204_hw4_library.CarPaymentStrategyPattern.PaySystem().
Referenced by ce204_hw4_app.Main.CustomerMenu().
removeMoney()
void ce204_hw4_library.PaymentSystemService.removeMoney (int costInput)
Removes the amount of money for a car rental. This method removes the amount of money for a car rental from the list of money amounts.
Parameters
costInput The amount of money to be removed.
Definition at line 60 of file PaymentSystemService.java.
                                         {
    money.remove(costInput);
  }
Referenced by ce204_hw4_app.Main.CustomerMenu().
setMoney()
void ce204_hw4_library.PaymentSystemService.setMoney (int costInput)
Sets the amount of money for a car rental. This method sets the amount of money for a car rental by adding it to the list of money amounts.
Parameters
costInput The amount of money for the car rental.
Definition at line 50 of file PaymentSystemService.java.
                                      {
    money.add(costInput);
  }
Referenced by ce204_hw4_app.Main.AdminMenu(), and ce204_hw4_app.Main.DefaulMainCars().
setSelectedCarIndex()
void ce204_hw4_library.PaymentSystemService.setSelectedCarIndex (int carIndexInput)
Sets the index of the selected car. This method sets the index of the selected car in the carIndex variable.
Parameters
carIndexInput The index of the selected car.
Definition at line 81 of file PaymentSystemService.java.
                                                     {
    carIndex = carIndexInput;
  }
Referenced by ce204_hw4_app.Main.CustomerMenu().
setStrategyPattern()
void ce204_hw4_library.PaymentSystemService.setStrategyPattern (CarPaymentStrategyPattern strategyPatternSelected)
Sets the payment strategy pattern. This method sets the payment strategy pattern to be used for the car rental payment.
Parameters
strategyPatternSelected The selected payment strategy pattern.
Definition at line 91 of file PaymentSystemService.java.
                                                                                    {
    strategyPattern = strategyPatternSelected;
  }
Referenced by ce204_hw4_app.Main.CustomerMenu().
The documentation for this class was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_library/PaymentSystemService.java