ce204_hw4_library.PayCreditCard Class Reference
Represents a credit card payment strategy for car rentals.
Public Member Functions
boolean PaymentDetails ()
Retrieves the payment details. This method retrieves the payment details for the credit card payment strategy.
void PaySystem (int price)
Performs the credit card payment. This method performs the credit card payment for the car rental.
void CollectPaymentSystemDetails ()
Collects the payment system details. This method collects the necessary details for the credit card payment system.
int getPrice ()
Retrieves the total amount of money available in the credit card. This method retrieves the total amount of money available in the credit card.
void setPrice (int i)
Sets the total amount of money available in the credit card. This method sets the total amount of money available in the credit card.
CreditCardSystem CreditCard ()
Retrieves the credit card system. This method retrieves the credit card system.
Detailed Description
Represents a credit card payment strategy for car rentals.
The PayCreditCard class implements the CarPaymentStrategyPattern interface and provides methods for handling credit card
payments for car rentals. It allows users to pay for their car rental using a credit card.
Definition at line 22 of file PayCreditCard.java.
Member Function Documentation
CollectPaymentSystemDetails()
void ce204_hw4_library.PayCreditCard.CollectPaymentSystemDetails ()
Collects the payment system details. This method collects the necessary details for the credit card payment system.
Implements ce204_hw4_library.CarPaymentStrategyPattern.
Definition at line 55 of file PayCreditCard.java.
                                            {
    creditCard = new CreditCardSystem("7845124233224471", "08/24", "778");
  }
CreditCard()
CreditCardSystem ce204_hw4_library.PayCreditCard.CreditCard ()
Retrieves the credit card system. This method retrieves the credit card system.
Returns
The credit card system.
Definition at line 84 of file PayCreditCard.java.
                                       {
    return creditCard;
  }
getPrice()
int ce204_hw4_library.PayCreditCard.getPrice ()
Retrieves the total amount of money available in the credit card. This method retrieves the total amount of money available in the credit card.
Returns
The total amount of money available in the credit card.
Definition at line 64 of file PayCreditCard.java.
                        {
    // TODO Auto-generated method stub
    return totalMoney;
  }
Referenced by ce204_hw4_library.PayCreditCard.PaySystem().
PaymentDetails()
boolean ce204_hw4_library.PayCreditCard.PaymentDetails ()
Retrieves the payment details. This method retrieves the payment details for the credit card payment strategy.
Returns
true, indicating that payment details are available.
Implements ce204_hw4_library.CarPaymentStrategyPattern.
Definition at line 33 of file PayCreditCard.java.
                                  {
    return true;
  }
PaySystem()
void ce204_hw4_library.PayCreditCard.PaySystem (int price)
Performs the credit card payment. This method performs the credit card payment for the car rental.
Parameters
price The amount of money used for the payment.
Implements ce204_hw4_library.CarPaymentStrategyPattern.
Definition at line 43 of file PayCreditCard.java.
                                   {
    System.out.println("Paying " + price + " using Credit Card.");
    setPrice(getPrice() - price);
    System.out.println(getPrice() + " remanined in the card.");
    System.out.println("You rented the car");
  }
References ce204_hw4_library.PayCreditCard.getPrice(), and ce204_hw4_library.PayCreditCard.setPrice().
setPrice()
void ce204_hw4_library.PayCreditCard.setPrice (int i)
Sets the total amount of money available in the credit card. This method sets the total amount of money available in the credit card.
Parameters
i The total amount of money to be set in the credit card.
Definition at line 74 of file PayCreditCard.java.
                              {
    // TODO Auto-generated method stub
    totalMoney = i;
  }
Referenced by ce204_hw4_library.PayCreditCard.PaySystem().
The documentation for this class was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_library/PayCreditCard.java