ce204_hw4_library.NotificationTime Class Reference
Represents a class that manages notification times for a customer.
Public Member Functions
int getRemainingNoti ()
Gets the remaining notification time.
void setRemainingNoti (int remainingTime)
Sets the remaining notification time.
NotificationTime (int remainingNoti, int reservationNoti)
Constructs a NotificationTime object.
Detailed Description
Represents a class that manages notification times for a customer.
Definition at line 14 of file NotificationTime.java.
Constructor & Destructor Documentation
NotificationTime()
ce204_hw4_library.NotificationTime.NotificationTime (int remainingNoti, int reservationNoti)
Constructs a NotificationTime object.
Parameters
remainingNoti The remaining notification time.
reservationNoti The reservation notification time.
Definition at line 61 of file NotificationTime.java.
                                                                  {
    this.remainingNoti = remainingNoti;
    this.reservationNoti = reservationNoti;
  }
Member Function Documentation
getRemainingNoti()
int ce204_hw4_library.NotificationTime.getRemainingNoti ()
Gets the remaining notification time.
Returns
The remaining notification time.
Definition at line 23 of file NotificationTime.java.
                                {
    return remainingNoti;
  }
Referenced by ce204_hw4_app.Main.CustomerMenu(), and ce204_hw4_library.CarCustomer.updateNoti().
setRemainingNoti()
void ce204_hw4_library.NotificationTime.setRemainingNoti (int remainingTime)
Sets the remaining notification time.
Parameters
remainingTime The remaining notification time to set.
Definition at line 32 of file NotificationTime.java.
                                                  {
    this.remainingNoti = remainingTime;
    if (remainingTime == 0) {
    } else {
      System.out.println(remainingTime);
    }
    checkRemainingNoti();
  }
Referenced by ce204_hw4_app.Main.CustomerMenu().
The documentation for this class was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_library/NotificationTime.java