ce204_hw4_library.CarPaymentStrategyPattern Interface Reference
Represents the payment strategy pattern for car rental.
Public Member Functions
boolean PaymentDetails ()
Verifies the payment details.
void PaySystem (int price)
Performs the payment using the specified price.
void CollectPaymentSystemDetails ()
Collects the payment system details from the user.
Detailed Description
Represents the payment strategy pattern for car rental.
Definition at line 14 of file CarPaymentStrategyPattern.java.
Member Function Documentation
CollectPaymentSystemDetails()
void ce204_hw4_library.CarPaymentStrategyPattern.CollectPaymentSystemDetails ()
Collects the payment system details from the user.
Implemented in ce204_hw4_library.PayPayPal, ce204_hw4_library.PayCreditCard, and ce204_hw4_library.PayCash.
Referenced by ce204_hw4_library.PaymentSystemService.proccessOrder().
PaymentDetails()
boolean ce204_hw4_library.CarPaymentStrategyPattern.PaymentDetails ()
Verifies the payment details.
Return values
[boolean] True if the payment details are valid, false otherwise.
Implemented in ce204_hw4_library.PayPayPal, ce204_hw4_library.PayCreditCard, and ce204_hw4_library.PayCash.
Referenced by ce204_hw4_library.PaymentSystemService.proccessOrder().
PaySystem()
void ce204_hw4_library.CarPaymentStrategyPattern.PaySystem (int price)
Performs the payment using the specified price.
Parameters
price The price of the car rental.
Implemented in ce204_hw4_library.PayPayPal, ce204_hw4_library.PayCreditCard, and ce204_hw4_library.PayCash.
Referenced by ce204_hw4_library.PaymentSystemService.proccessOrder().
The documentation for this interface was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_library/CarPaymentStrategyPattern.java