ce204_hw4_library.RentCarInterface Interface Reference
Represents the interface for rental car information.
Public Member Functions
int getCarSeatsNumber ()
Gets the number of seats in the car. This method returns the number of seats in the car.
String getCarBrand ()
Gets the brand of the car. This method returns the brand of the car.
String getCarColor ()
Gets the color of the car. This method returns the color of the car.
String getCarModel ()
Gets the model of the car. This method returns the model of the car.
int getCarPrice ()
Gets the price of renting the car. This method returns the price of renting the car.
int getCarModelYear ()
Gets the model year of the car. This method returns the model year of the car.
String getCarFuelType ()
Gets the fuel type of the car. This method returns the fuel type of the car.
Detailed Description
Represents the interface for rental car information.
The RentCarInterface defines the methods for accessing various details of a rental car.
Definition at line 17 of file RentCarInterface.java.
Member Function Documentation
getCarBrand()
String ce204_hw4_library.RentCarInterface.getCarBrand ()
Gets the brand of the car. This method returns the brand of the car.
Returns
The brand of the car.
Implemented in ce204_hw4_library.CarModelSUV, ce204_hw4_library.CarModelStationWagon, ce204_hw4_library.CarModelSedan, ce204_hw4_library.CarModelPickUp, ce204_hw4_library.CarModelHatchback, and ce204_hw4_library.CarModelCabrio.
Referenced by ce204_hw4_app.Bill.displayBill(), and ce204_hw4_app.Main.displayCar().
getCarColor()
String ce204_hw4_library.RentCarInterface.getCarColor ()
Gets the color of the car. This method returns the color of the car.
Returns
The color of the car.
Implemented in ce204_hw4_library.CarModelSUV, ce204_hw4_library.CarModelStationWagon, ce204_hw4_library.CarModelSedan, ce204_hw4_library.CarModelPickUp, ce204_hw4_library.CarModelHatchback, and ce204_hw4_library.CarModelCabrio.
Referenced by ce204_hw4_app.Bill.displayBill(), and ce204_hw4_app.Main.displayCar().
getCarFuelType()
String ce204_hw4_library.RentCarInterface.getCarFuelType ()
Gets the fuel type of the car. This method returns the fuel type of the car.
Returns
The fuel type of the car.
Implemented in ce204_hw4_library.CarModelSUV, ce204_hw4_library.CarModelStationWagon, ce204_hw4_library.CarModelSedan, ce204_hw4_library.CarModelPickUp, ce204_hw4_library.CarModelHatchback, and ce204_hw4_library.CarModelCabrio.
Referenced by ce204_hw4_app.Bill.displayBill(), and ce204_hw4_app.Main.displayCar().
getCarModel()
String ce204_hw4_library.RentCarInterface.getCarModel ()
Gets the model of the car. This method returns the model of the car.
Returns
The model of the car.
Implemented in ce204_hw4_library.CarModelSUV, ce204_hw4_library.CarModelStationWagon, ce204_hw4_library.CarModelSedan, ce204_hw4_library.CarModelPickUp, ce204_hw4_library.CarModelHatchback, and ce204_hw4_library.CarModelCabrio.
Referenced by ce204_hw4_app.Bill.displayBill(), and ce204_hw4_app.Main.displayCar().
getCarModelYear()
int ce204_hw4_library.RentCarInterface.getCarModelYear ()
Gets the model year of the car. This method returns the model year of the car.
Returns
The model year of the car.
Implemented in ce204_hw4_library.CarModelSUV, ce204_hw4_library.CarModelStationWagon, ce204_hw4_library.CarModelSedan, ce204_hw4_library.CarModelPickUp, ce204_hw4_library.CarModelHatchback, and ce204_hw4_library.CarModelCabrio.
Referenced by ce204_hw4_app.Bill.displayBill().
getCarPrice()
int ce204_hw4_library.RentCarInterface.getCarPrice ()
Gets the price of renting the car. This method returns the price of renting the car.
Returns
The price of renting the car.
Implemented in ce204_hw4_library.CarModelSUV, ce204_hw4_library.CarModelStationWagon, ce204_hw4_library.CarModelSedan, ce204_hw4_library.CarModelPickUp, ce204_hw4_library.CarModelHatchback, and ce204_hw4_library.CarModelCabrio.
Referenced by ce204_hw4_app.Bill.displayBill(), and ce204_hw4_app.Main.displayCar().
getCarSeatsNumber()
int ce204_hw4_library.RentCarInterface.getCarSeatsNumber ()
Gets the number of seats in the car. This method returns the number of seats in the car.
Returns
The number of seats in the car.
Implemented in ce204_hw4_library.CarModelSUV, ce204_hw4_library.CarModelStationWagon, ce204_hw4_library.CarModelSedan, ce204_hw4_library.CarModelPickUp, ce204_hw4_library.CarModelHatchback, and ce204_hw4_library.CarModelCabrio.
Referenced by ce204_hw4_app.Bill.displayBill(), and ce204_hw4_app.Main.displayCar().
The documentation for this interface was generated from the following file:
ce204-hw4-alper-sahin/src/main/java/ce204_hw4_library/RentCarInterface.java